
def defaultHeading(serverkey,log):
	defaultHeading = '''
#Generated By Template Donot Edit the File Directly
key = "{0}"
# Accounting records log file
accounting file = /var/log/tacacs/tac_plus.acct
'''.format(serverkey)

	return defaultHeading


def commentGen(commentname):
	comment  = "########################### {0} ####################################".format(commentname)
	return comment

def userHeading():
	userHeading = '''
{0}
user = DEFAULT {{
        default service = deny
        #cmd = exit {{ permit .* }}
}}'''.format(commentGen("USERS"))
	return userHeading

def users(username,groupname):
	defaultTemplate = '''
user = {0} {{ member = {1} }}'''.format(username,groupname)
	return defaultTemplate


def group(groupname,defaultservice,services,parent,member,aclname,logintype,remarks):

	if parent == 'Y':
		group = '''
group = {0} {{
        default service = {1}
        login = {2}
	{3}
}}'''.format(groupname,defaultservice,logintype,services)

	else:
		if services:
			group = '''
group = {0} {{
	login = {1}
	{2}
	member = {3}
}}'''.format(groupname,logintype,services,member)
		else:
			group = '''
group = {0} {{
	login = {1}
	member = {2}
	acl = {3}
}}'''.format(groupname,logintype,member,aclname)


	return group
